### ISSUE TITLE
Test whitelisting

### ISSUE THREAD

**Issue by schmoelder** [modsim/CADET-CLA-test-2#4]
Hey, I like this approach (a lot).

To make this a bit more practical, could we also whitelist some individual users (e.g. Sam) and all users with an *@fz-juelich.de address?

**Comment by ronald-jaepel** [comment]
We can whitelist explicit users, but not groups.

**Comment by ronald-jaepel** [comment]
this line does the white-listing. You can use star notation, but GitHub usernames don't contain the email domain info.
https://github.com/modsim/CADET-CLA-test-2/blob/a0ce8e5a7565984a7f584fb9a6f0fc97a5076068/.github/workflows/cla.yml#L32
